# Generated by Django 3.2.12 on 2022-03-11 13:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ItemPropContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=list, size=None)),
                ('is_generated', models.BooleanField(default=False)),
                ('subsection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sveden.subsection')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ItemProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_prop', models.CharField(max_length=255)),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sveden.itempropcontainer')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ChildItemProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('item_prop', models.CharField(max_length=255)),
                ('show_position', models.PositiveIntegerField()),
                ('value_position', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sveden.itemprop')),
            ],
            options={
                'ordering': ('show_position', 'id'),
            },
        ),
    ]
