# Generated by Django 3.2.12 on 2022-02-28 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа публикации', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.AddField(
            model_name='article',
            name='workload',
            field=models.FloatField(help_text='Объем работы', null=True),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Фамилия и инициалы автора', max_length=256)),
                ('weight', models.FloatField(help_text='Вклад автора в работу')),
                ('order', models.PositiveIntegerField(help_text='Позиция в авторах публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления')),
                ('article', models.ForeignKey(help_text='Публикация', on_delete=django.db.models.deletion.CASCADE, to='eleden.article')),
                ('user', models.ForeignKey(help_text='Идентификатор пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.ForeignKey(default=None, help_text='Тип публикации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleden.articlekind'),
        ),
        # migrations.AlterField(
        #     model_name='article',
        #     name='users',
        #     field=models.ManyToManyField(
        #           help_text='Зарегистрированные авторы публикации',
        #           related_name='articles',
        #           through='eleden.Author',
        #           to=settings.AUTH_USER_MODEL
        #     ),
        # ),
        migrations.RemoveField(
            model_name='article',
            name='users'
        ),
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(
                help_text='Зарегистрированные авторы публикации',
                related_name='articles',
                through='eleden.Author',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
